import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";

const here = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(here, "../..");
const shared = path.join(app, "Shared/src");
const customers = path.join(shared, "modules/customer/customers");
const fnDir = path.join(app, "SubsTrack/supabase/functions/customer-status");
const outDir = path.join(fnDir, "_generated");
const dashboardDir = path.join(outDir, "dashboard");

// Deno gets one self-contained bundle, so any npm package import is a mistake.
const sharedOnly = {
  name: "shared-only",
  enforce: "pre",
  resolveId(source, importer) {
    if (!importer) return null;
    if (/^https?:\/\//.test(source)) return { id: source, external: true };
    if (source.startsWith(".") || source.startsWith("@shared/")) return null;
    if (path.isAbsolute(source)) return null;
    this.error(`${source} (imported by ${importer}) is not Shared code`);
  },
};

function bundle(outputDir, entry, emptyOutDir, banner) {
  return build({
    configFile: false,
    logLevel: "warn",
    plugins: [sharedOnly],
    resolve: {
      alias: [{ find: /^@shared\//, replacement: `${shared}/` }],
    },
    build: {
      outDir: outputDir,
      emptyOutDir,
      copyPublicDir: false,
      minify: false,
      target: "es2022",
      lib: {
        entry,
        formats: ["es"],
        fileName: (_format, name) =>
          name === "index" ? "index.ts" : `${name}.js`,
      },
      rolldownOptions: { output: { banner } },
    },
  });
}

await bundle(
  outDir,
  {
    customerStatus: path.join(customers, "utils/customerStatusPage.ts"),
    customerSelect: path.join(customers, "repository/customerSelect.ts"),
  },
  true,
  "",
);

await bundle(
  dashboardDir,
  { index: path.join(fnDir, "index.ts") },
  false,
  "// @ts-nocheck — generated by Web/scripts/build-edge.mjs; paste into the Dashboard.",
);

console.log(`customer-status bundle written to ${path.relative(app, outDir)}`);
console.log(
  `one-file copy for the Dashboard: ${path.relative(app, path.join(dashboardDir, "index.ts"))}`,
);
