import type { BranchFilter } from '@/src/core/constants';
import type { DbCharge, DbChargeBalance } from '@/src/core/types/db';

/**
 * A bill to raise. `id` travels WITH the payload rather than being generated by
 * the repository: a month charge derives a deterministic id from
 * (customer_plan_id, billing_month), so two devices collecting the same month
 * offline converge on one row instead of duplicating it.
 */
export type CreateChargePayload = Omit<
  DbCharge,
  | 'created_at'
  | 'updated_at'
  | 'voided_at'
  | 'voided_by'
  | 'void_reason'
  | 'written_off_at'
  | 'written_off_by'
  | 'write_off_reason'
  | 'customers'
  | 'customer_plans'
  | 'sales'
>;

/** The editable face of a bill. Its kind, its keys and its dates never move. */
export type UpdateChargePayload = Partial<
  Pick<DbCharge, 'amount' | 'currency_id' | 'rate_per_usd_snapshot' | 'due_date' | 'description' | 'notes'>
>;

/**
 * A bill paired with what has reached it.
 *
 * The two travel together because the ONE query that reads a set of bills
 * already has the sum in hand — asking for the bills and then asking for their
 * balances cost a second read that bound one parameter per bill.
 */
export interface DbChargeWithPaid {
  charge: DbCharge;
  paid: number;
}

export interface FindChargesOptions {
  customerId?: string;
  customerIds?: string[];
  branchFilter?: BranchFilter;
  kinds?: DbCharge['kind'][];
}

export interface IChargeRepository {
  findById(id: string): Promise<DbCharge | null>;
  findByIds(ids: string[]): Promise<DbCharge[]>;
  findMonthChargesForLines(customerPlanIds: string[]): Promise<DbChargeWithPaid[]>;
  findMonthChargesForCustomer(customerId: string): Promise<DbChargeWithPaid[]>;
  findBySaleId(saleId: string): Promise<DbCharge | null>;
  findBySaleIds(saleIds: string[]): Promise<DbCharge[]>;
  findOpenWithPaid(opts: FindChargesOptions): Promise<DbChargeWithPaid[]>;

  balances(chargeIds: string[]): Promise<DbChargeBalance[]>;

  create(payload: CreateChargePayload): Promise<DbCharge>;
  ensure(payload: CreateChargePayload): Promise<DbCharge>;
  update(id: string, values: UpdateChargePayload): Promise<DbCharge>;

  void(id: string, voidedBy: string, reason: string | null): Promise<DbCharge>;
  writeOff(id: string, writtenOffBy: string, reason: string | null): Promise<DbCharge>;

  writtenOffInRange(
    startIso: string,
    endExclusiveIso: string,
    branchFilter: BranchFilter,
  ): Promise<DbCharge[]>;
}
