import type { BranchFilter } from '@/src/core/constants';
import type { DbCharge, DbChargeBalance } from '@/src/core/types/db';

/**
 * A bill to raise. `id` travels WITH the payload rather than being generated by
 * the repository: a month charge derives a deterministic id from
 * (customer_plan_id, billing_month), so two devices collecting the same month
 * offline converge on one row instead of duplicating it.
 */
export type CreateChargePayload = Omit<
  DbCharge,
  | 'created_at'
  | 'updated_at'
  | 'voided_at'
  | 'voided_by'
  | 'void_reason'
  | 'written_off_at'
  | 'written_off_by'
  | 'write_off_reason'
  | 'customers'
  | 'customer_plans'
  | 'sales'
>;

/** The editable face of a bill. Its kind, its keys and its dates never move. */
export type UpdateChargePayload = Partial<
  Pick<DbCharge, 'amount' | 'currency_id' | 'rate_per_usd_snapshot' | 'due_date' | 'description' | 'notes'>
>;

export interface FindChargesOptions {
  customerId?: string;
  customerIds?: string[];
  branchFilter?: BranchFilter;
  /** Bills with money still owed on them (via charge_balances). */
  openOnly?: boolean;
  kinds?: DbCharge['kind'][];
}

export interface IChargeRepository {
  findById(id: string): Promise<DbCharge | null>;
  findByIds(ids: string[]): Promise<DbCharge[]>;
  /** Every non-voided month bill for these service lines — the grid's input. */
  findMonthChargesForLines(customerPlanIds: string[]): Promise<DbCharge[]>;
  /** Every non-voided month bill for a customer, all years. */
  findMonthChargesForCustomer(customerId: string): Promise<DbCharge[]>;
  findBySaleId(saleId: string): Promise<DbCharge | null>;
  /** The bills of a page of sales — one read instead of one per row. */
  findBySaleIds(saleIds: string[]): Promise<DbCharge[]>;
  find(opts: FindChargesOptions): Promise<DbCharge[]>;

  /**
   * How much has been collected against these bills. Server: the
   * `charge_balances` view. Offline: the same GROUP BY over the mirror. Both
   * exclude voided and written-off bills at source, so a caller never filters.
   */
  balances(chargeIds: string[]): Promise<DbChargeBalance[]>;
  /** Every live bill with a balance > 0, for the debts view and the waterfall. */
  openBalances(opts: FindChargesOptions): Promise<DbChargeBalance[]>;

  create(payload: CreateChargePayload): Promise<DbCharge>;
  /** Upsert by id — a month bill may already exist from another device. */
  ensure(payload: CreateChargePayload): Promise<DbCharge>;
  update(id: string, values: UpdateChargePayload): Promise<DbCharge>;

  /** The bill was a mistake. Refused by the service when money sits on it. */
  void(id: string, voidedBy: string, reason: string | null): Promise<DbCharge>;
  /** The bill is real but lost. Keeps the row and reports it as a loss. */
  writeOff(id: string, writtenOffBy: string, reason: string | null): Promise<DbCharge>;

  /** Written-off bills in a period — the Reports "lost to unpaid debts" line. */
  writtenOffInRange(
    startIso: string,
    endExclusiveIso: string,
    branchFilter: BranchFilter,
  ): Promise<DbCharge[]>;
}
